# Generated by Django 4.2.7 on 2024-06-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailing_create_date_alter_mailing_sent_time_and_more'),
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('set_user_deactivate', 'Can deactivate user'), ('view_all_users', 'просмотр всех пользователей')], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]