# Generated by Django 4.2.7 on 2024-06-28 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try_date', models.DateField(blank=True, null=True, verbose_name='время последней попытки')),
                ('try_status', models.CharField(blank=True, choices=[('success', 'успешно'), ('fail', 'неуспешно')], default='', max_length=30, null=True, verbose_name='статус попытки')),
                ('response', models.CharField(blank=True, max_length=300, null=True, verbose_name='ответ сервера')),
            ],
            options={
                'verbose_name': 'попытка отправки',
                'verbose_name_plural': 'попытки отправки',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_name', models.CharField(max_length=100, verbose_name='название рассылки')),
                ('create_date', models.DateField(default=datetime.datetime(2024, 2, 7, 10, 22, 11, 621203, tzinfo=datetime.timezone.utc), verbose_name='дата и время создания рассылки')),
                ('sent_time', models.DateField(blank=True, default=datetime.datetime(2024, 2, 7, 10, 22, 11, 621331, tzinfo=datetime.timezone.utc), null=True, verbose_name='время отправки рассылки')),
                ('periodicity', models.CharField(choices=[('0', 'один раз'), ('1', 'ежедневно'), ('7', 'еженедельно'), ('30', 'ежемесячно')], default='', max_length=50, verbose_name='периодичность рассылки')),
                ('mailing_status', models.CharField(choices=[('completed', 'завершена'), ('created', 'создана'), ('launched', 'запущена')], default='created', max_length=30, verbose_name='статус рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='тема сообщения')),
                ('message', models.TextField(max_length=500, verbose_name='тело сообщения')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
    ]