# Generated by Django 4.2.7 on 2024-06-29 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_deactivate', 'Can deactivate mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.RenameField(
            model_name='logs',
            old_name='response',
            new_name='server_response',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='mailing',
        ),
        migrations.AddField(
            model_name='logs',
            name='mailing_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailing', verbose_name='имя рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 18, 15, 20, 16, 87003, tzinfo=datetime.timezone.utc), verbose_name='дата и время создания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='sent_time',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 18, 15, 20, 16, 87147, tzinfo=datetime.timezone.utc), null=True, verbose_name='время отправки рассылки'),
        ),
    ]