# Generated by Django 4.2.7 on 2024-06-29 12:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0003_alter_mailing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 19, 18, 22, 53, 4584, tzinfo=datetime.timezone.utc), verbose_name='дата и время создания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='sent_time',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 19, 18, 22, 53, 4763, tzinfo=datetime.timezone.utc), null=True, verbose_name='время отправки рассылки'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='ФИО')),
                ('client_email', models.EmailField(max_length=254, verbose_name='почта клиента')),
                ('comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='комментарий')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'unique_together': {('owner', 'client_email')},
            },
        ),
        migrations.AlterField(
            model_name='mailing',
            name='mail_to',
            field=models.ManyToManyField(to='mailing.client', verbose_name='клиенты'),
        ),
    ]