# Generated by Django 4.2.7 on 2024-06-29 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailing_create_date_alter_mailing_sent_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата и время создания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='sent_time',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='время отправки рассылки'),
        ),
    ]